### ISSUE TITLE
Translation into Chinese

### ISSUE THREAD

**Issue by gavinfish** [shekhargulati/java8-the-missing-tutorial#17]
Hi, shekhargulati!

I am really like your posts in java8-the-missing-tutorial. I want to translate them into Chinese so that more people can learn about them. I will add your name and links to this repository. Can you give me a chance?

**Comment by shekhargulati** [comment]
Hello @gavinfish yes please go ahead. Let me know when you are done I will add link to Chinese translation to the repo as well.

**Comment by yjqg6666** [comment]
any update on the translation progress? @gavinfish

**Comment by gavinfish** [comment]
Here are some chapters [java8-the-missing-tutorial-zh](https://github.com/gavinfish/java8-the-missing-tutorial-zh)  @yjqg6666

**Comment by yjqg6666** [comment]
I suggest that this issue could be closed.
